-- 코드를 입력하세요
SELECT b.TITLE, b.BOARD_ID, r.REPLY_ID, r.WRITER_ID, r.CONTENTS, DATE_FORMAT(r.CREATED_DATE, '%Y-%m-%d') as CREATED_DATE
FROM USED_GOODS_BOARD as b inner join USED_GOODS_REPLY as r
on b.BOARD_ID = r.BOARD_ID
where b.CREATED_DATE between '2022-10-01' and '2022-10-31'
ORDER BY r.CREATED_DATE, b.TITLE;